import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout/Layout';
import Home from '../components/layout/Home';
import styles from '../styles/Home.module.css';

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bookings App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
      </Layout>
    </div>
  );
}
